version: "3.6"
services:
  postgres:
    container_name: "postgres"
    image: postgres:alpine3.16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
  hapi:
    container_name: "hapi"
    image: node:16.15.1
    ports:
      - "9090:9090"
    volumes:
      - ./tmp/hapi/node_modules/:/app/node_modules/
      - type: bind
        source: ./hapi
        target: /app
    working_dir: /app
    command: bash -c "yarn && yarn start:dev"
    environment:
      HAPI_SERVER_PORT: "${HAPI_SERVER_PORT}"
      HAPI_SERVER_ADDRESS: "${HAPI_SERVER_ADDRESS}"
      HAPI_NETWORK_CHAIN_ID: "${HAPI_NETWORK_CHAIN_ID}"
      HAPI_NETWORK_API: "${HAPI_NETWORK_API}"
      HAPI_HASURA_URL: "${HAPI_HASURA_URL}"
      HAPI_HASURA_ADMIN_SECRET: "${HAPI_HASURA_ADMIN_SECRET}"
      HAPI_HYPERION_API: "${HAPI_HYPERION_API}"
      HAPI_HYPERION_START_AT: "${HAPI_HYPERION_START_AT}"
      HAPI_VMPX_CONTRACT: "${HAPI_VMPX_CONTRACT}"
      HAPI_DISPENSER_CONTRACT: "${HAPI_DISPENSER_CONTRACT}"
      HAPI_DISPENSER_CONTRACT_PUBLIC_KEY: "${HAPI_DISPENSER_CONTRACT_PUBLIC_KEY}"
      HAPI_DISPENSER_CONTRACT_PRIVATE_KEY: "${HAPI_DISPENSER_CONTRACT_PRIVATE_KEY}"
      HAPI_ETH_HTTP_ENDPOINT: "${HAPI_ETH_HTTP_ENDPOINT}"
      HAPI_ETH_WSS_ENDPOINT: "${HAPI_ETH_WSS_ENDPOINT}"
      HAPI_ETH_ALCHEMY_KEY: "${HAPI_ETH_ALCHEMY_KEY}"
      HAPI_ETH_WALLET_TOKEN_ADDRESS: "${HAPI_ETH_WALLET_TOKEN_ADDRESS}"
      HAPI_ETH_WALLET_ADDRESS: "${HAPI_ETH_WALLET_ADDRESS}"
      HAPI_ETH_WALLET_KEY: "${HAPI_ETH_WALLET_KEY}"
      HAPI_ETH_START_BLOCK_NUMBER: "${HAPI_ETH_START_BLOCK_NUMBER}"
      HAPI_ETH_MAX_RETRY_SEND_TX: "${HAPI_ETH_MAX_RETRY_SEND_TX}"
      HAPI_ETH_BLOCKS_TO_FETCH_BY_CATCHER: "${HAPI_ETH_BLOCKS_TO_FETCH_BY_CATCHER}"
      HAPI_ETH_INTERVAL_FETCHER_SEC: "${HAPI_ETH_INTERVAL_FETCHER_SEC}"
      HAPI_ETH_MAX_TIME_HYPERION_ACTION_SEC: "${HAPI_ETH_MAX_TIME_HYPERION_ACTION_SEC}"
  hasura:
    container_name: "hasura"
    image: hasura/graphql-engine:v2.30.1.cli-migrations-v3
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    volumes:
      - ./hasura/migrations:/migrations
      - ./hasura/metadata:/metadata
      - ./hasura/seeds:/seeds
    environment:
      HASURA_GRAPHQL_SERVER_PORT: ${HASURA_GRAPHQL_SERVER_PORT}
      HASURA_GRAPHQL_DATABASE_URL: "${HASURA_GRAPHQL_DATABASE_URL}"
      HASURA_GRAPHQL_MIGRATIONS_DIR: /migrations
      HASURA_GRAPHQL_METADATA_DIR: /metadata
      HASURA_GRAPHQL_SEEDS_DIR: /seeds
      HASURA_GRAPHQL_ACTION_BASE_URL: "${HASURA_GRAPHQL_ACTION_BASE_URL}"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      # Local Development Configurations It is recommended to disable this in production
      # HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_LOGGING: "true"
      # disabled security for local development
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}"
volumes:
  postgres_data:
