apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  # postgres
  POSTGRES_USER: '${POSTGRES_USER}'
  POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
  POSTGRES_DB: '${POSTGRES_DB}'
  POSTGRES_DATA: '${POSTGRES_DATA}'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hapi-config
data:
  # hapi
  GOOGLE_APPLICATION_CREDENTIALS: '${GOOGLE_CREDENTIALS_JSON}'
  HAPI_HASURA_ADMIN_SECRET: '${HAPI_HASURA_ADMIN_SECRET}'
  HAPI_JWT_MAX_TTL_SEC: '${HAPI_JWT_MAX_TTL_SEC}'
  HAPI_JWT_RT_TTL_SEC: '${HAPI_JWT_RT_TTL_SEC}'
  HAPI_SERVER_ADDRESS: '${HAPI_SERVER_ADDRESS}'
  HAPI_SERVER_PORT: '${HAPI_SERVER_PORT}'
  HAPI_JWT_TTL_SEC: '${HAPI_JWT_TTL_SEC}'
  HAPI_HASURA_URL: '${HAPI_HASURA_URL}'
  HAPI_JWT_SECRET: '${HAPI_JWT_SECRET}'
  HAPI_ROOT_URL: '${HAPI_ROOT_URL}'
  HAPI_JWT_ISS: '${HAPI_JWT_ISS}'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hasura-config
data:
  # hasura
  HASURA_GRAPHQL_ENABLE_CONSOLE: '${HASURA_GRAPHQL_ENABLE_CONSOLE}'
  HASURA_GRAPHQL_DATABASE_URL: '${HASURA_GRAPHQL_DATABASE_URL}'
  HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET}'
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: '${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}'
  HASURA_GRAPHQL_ACTION_BASE_URL: '${HASURA_GRAPHQL_ACTION_BASE_URL}'